name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Truncate String
      uses: 2428392/gh-truncate-string-action@v1.1.0
      id: truncatedString
      with:
        stringToTruncate: "${{ github.sha }}"
        maxLength: 7
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Containerfile --tag update_dh_dns:"${{ steps.truncatedString.outputs.string }}"
    - name: Login to Quay.io
      run: docker login -u="hyclak+githubcicd" -p="${{ QUAY_IO_TOKEN }}" quay.io